In [2]:
import pandas as pd

In [8]:
df=pd.read_csv("student_scores.csv")

In [9]:
df

     name gender  age  math_score  english_score  science_score
0     Ali      M   16        78.0           82.0           89.0
1    Sara      F   15        88.0            NaN           93.0
2   Ahmed      M   17         NaN           74.0           80.0
3    Zara      F   16        90.0           91.0            NaN
4  Faisal      M   15        45.0           40.0           38.0
5    Amna      F   17        80.0           87.0           85.0

In [12]:
df['math_score'].mean()
df['english_score'].mean()
df['science_score'].mean()

77.0

In [13]:
df['sum_Score']=df['math_score']+df['english_score']+df['science_score']

In [14]:
df

     name gender  age  math_score  english_score  science_score  sum_Score
0     Ali      M   16        78.0           82.0           89.0      249.0
1    Sara      F   15        88.0            NaN           93.0        NaN
2   Ahmed      M   17         NaN           74.0           80.0        NaN
3    Zara      F   16        90.0           91.0            NaN        NaN
4  Faisal      M   15        45.0           40.0           38.0      123.0
5    Amna      F   17        80.0           87.0           85.0      252.0

In [15]:
df.isnull().sum()

name             0
gender           0
age              0
math_score       1
english_score    1
science_score    1
sum_Score        3
dtype: int64

In [34]:
df.fillna(0,inplace=True)

In [35]:
df.max()

name              Zara
gender               M
age                 17
math_score        90.0
english_score     91.0
science_score     93.0
sum_Score        252.0
grade                C
dtype: object

In [36]:
df.groupby('gender')['sum_Score'].mean()

gender
F     84.0
M    124.0
Name: sum_Score, dtype: float64

In [37]:
def grade_ass(score):
  if score>250:
    return 'A'
  elif score>200:
    return 'B'
  else:
    return 'C'

df['grade']=df['sum_Score'].apply(grade_ass)

In [38]:
df

,name,gender,age,math_score,english_score,science_score,sum_Score,grade
0,Ali,M,16,78.0,82.0,89.0,249.0,B
1,Sara,F,15,88.0,0.0,93.0,0.0,C
2,Ahmed,M,17,0.0,74.0,80.0,0.0,C
3,Zara,F,16,90.0,91.0,0.0,0.0,C
4,Faisal,M,15,45.0,40.0,38.0,123.0,C
5,Amna,F,17,80.0,87.0,85.0,252.0,A

In [40]:
df.to_csv('student_scores_updated.csv')